Support change owner address
Zondax/ledger-filecoin pull request #84
Opened 2021-11-03 12:26 UTC by ftheirs

Added support for ChangeOwnerAddress (Method 23).
Parser accepts ByteStringType parameters now.
Added test cases for ChangeOwnerAddress

2021-11-04 12:31 UTC, rllola requested changes

2021-11-04 12:31 UTC, rllola commented on tests/testvectors/manual.json
> +        "encoded_tx_hex": "8A004300EC075501DFE49184D46ADC8F89D44638BEB45F78FCAD259001401A000F4240430009C4430009C41757815501DFE49184D46ADC8F89D44638BEB45F78FCAD2590"
Like we discussed this encoded cbor tx is incorrect. The parameter __should__ not be an array for this method. Instead of removing it we could marked it as `"valid": false` so we won't forget.

2021-11-12 19:02 UTC, ftheirs commented on tests/testvectors/manual.json
> +        "encoded_tx_hex": "8A004300EC075501DFE49184D46ADC8F89D44638BEB45F78FCAD259001401A000F4240430009C4430009C41757815501DFE49184D46ADC8F89D44638BEB45F78FCAD2590"
Done! Thanks Lola!

2021-12-18 15:15 UTC, jleni requested changes
The version number need to be updated before we can merge

2021-12-21 23:24 UTC, jleni approved these changes

2021-12-21 23:24 UTC, merged